language: ruby
os: [osx, linux]
osx_image: xcode9.3
rvm:
  - 2.4.1
addons:
  apt:
    packages:
      - dirmngr
      - gnupg2
before_install:
  - unset BUNDLE_GEMFILE
  - rvm get head
  - rvm alias delete default
  - hash -r
  - rm ~/.rvm/hooks/after_use
install: gem install tf -v '>=0.4.1'
script: 'NOEXEC=skip tf --text $TEST'
env:
  - TEST=fast/*
  - TEST=long/named_ruby_and_gemsets_comment_test.sh
  - TEST=long/truffleruby_comment_test.sh
