language: ruby
os: osx
osx_image: xcode9.4
rvm:
  - 2.4
install: gem install tf -v '>=0.4.1'
script:
  - rvm get head
  - rvm autolibs enabled
  - tf --text $TEST
  - cat '/Users/travis/.rvm/log/*/configure.log'
env:
  - TEST=long/named_ruby_and_gemsets_comment_test.sh

