language: ruby
os: osx
osx_image: xcode9.3
rvm:
  - 2.4
addons:
  apt:
    packages:
      - dirmngr
      - gnupg2
      - gawk
      - libgmp-dev
install: gem install tf -v '>=0.4.1'
script: 'echo hello'

