language: ruby
os: osx
osx_image: xcode9.4
rvm:
  - 2.4
install: gem install tf -v '>=0.4.1'
script: 'NOEXEC=skip tf --text $TEST'
env:
  - TEST=fast/*
  - TEST=long/named_ruby_and_gemsets_comment_test.sh
  - TEST=long/truffleruby_comment_test.sh

